---
title: "Developing Data Product - Course Project"
author: "Tiago Berti"
date: "August, 21st 2017"
output: ioslides_presentation
---

##Storm Database Explorer

[shinyapp](https://tiagocberti.shinyapps.io/DevDataProd_project)
This presentation is being created as part of the peer assessment for the coursera developing data products class. The assignment is geared toward ensuring the following concepts were well understood by the students

- **shiny** to build data product application
- **R-Presentation or slidify** to create data product related presentations

##The Application
To display the understanding of using **shiny** to build an application, a simple application called **Storm Database Explorer** has been developed and deployed at: 
https://senthilkumar-k.shinyapps.io/DevDataProd-CourseProject/

The application allows the user to:
- Select the inputs like- the range of years, types of events. 
- Select the output to be displayed on the map, or as a graph, or as a table 
  - Also has a option to download the filtered data.


##The Data
This application is based on the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database.

Dataset has been obtained from [here](https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2) and processed for the course project. This is the same file we used for the Cousera's Reproducible Research Course.

Source code for the project is available on the [GitHub](https://github.com/Senthilkumar-k/DevDataProd-CourseProject).


##Data
Read Data
```{r}
library(data.table)
#dt <- fread('events.agg.csv')
#head(dt)
```